### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [vasaaa1993/BSA17_1#4]
@vasaaa1993, порядок, продовжуй, все виходить. Можливо **README.md** докинеш з описом репозиторію і лінками на статті? Не обов'язково, але якшо надумаєш таки зробити, то коммітни з повідомленням **"Added README.md (fixes #4)"**, щоб **GitHub** автоматично закрив цю проблему.

**Comment by vasaaa1993** [comment]
Дякую, зараз спробую
